t = int(input('escreva um numero'))
print('='*10)
print('A tabuada de {}:'.format(t))
print('{}* 1={:2}'.format(t,t*1))
print('{}* 2={:2}'.format(t,t*2))
print('{}* 3={:2}'.format(t,t*3))
print('{}* 4={:2}'.format(t,t*4))
print('{}* 5={:2}'.format(t,t*5))
print('{}* 6={:2}'.format(t,t*6))
print('{}* 7={:2}'.format(t,t*7))
print('{}* 8={:2}'.format(t,t*8))
print('{}* 9={:2}'.format(t,t*9))
print('{}*10={:2}'.format(t,t*10))
print('='*10)